---
version: 2.1

jobs:
  serverInstall:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: node --version

workflows:
  version: 2
  test_all:
    jobs:
      - serverInstall