---
version: 2

jobs:
  serverInstall:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: mkdir -p my_workspace
      - run: node --version
      - run: npm install
      - persist_to_workspace:
        root: admin_app
        paths:
          - echo-output

  integrationTests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: admin_app
      - run: npm run test:unit
      - run: npm run build

#  autoDeploy:
#    docker:
#      image: circleci/node:latest
#    steps:
#      - checkout
#      - aws-s3/sync:
#          from: dist
#          to: 's3://admin-dev.mindlogger.org'
#          overwrite: true

workflows:
  version: 2
  test_all:
    jobs:
      - serverInstall
      - integrationTests:
          requires:
            - serverInstall
#      - autoDeploy:
#          requires:
#            - serverInstall
#          filters:
#            branches:
#              only: master