---
version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.0
  node: circleci/node@10

jobs:
  serverInstall:
    docker:
      image: circleci/node:latest
    steps:
      - checkout
      - run: node --version
      - run: npm install

  integrationTests:
    docker:
      image: circleci/node:latest
    steps:
      - run: npm run test:unit
      - run: npm run build

  autoDeploy:
    docker:
      image: circleci/node:latest
    steps:
      - checkout
      - aws-s3/sync:
          from: dist
          to: 's3://admin-dev.mindlogger.org'
          overwrite: true

workflows:
  test_all:
    jobs:
      - serverInstall
      - integrationTests:
          requires:
            - serverInstall
      - autoDeploy:
          requires:
            - integrationTests
          filters:
            branches:
              only: master