---
version: 2.1

jobs:
  serverInstall:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: node --version
      - run: npm install
  integrationTest:
    steps:
      - run: npm run test:unit
      - run: npm run build

workflows:
  test_all:
    jobs:
      - serverInstall
      - integrationTest:
          requires:
            - serverInstall