export default {
  choices: 'reprolib:terms/choices',
  value: 'reprolib:terms/value',
  inputType: 'reprolib:terms/inputType',
  valueType: 'reprolib:terms/valueType',
  multipleChoice: 'reprolib:terms/multipleChoice',
  order: 'reprolib:terms/order',
  responseOptions: 'reprolib:terms/responseOptions',
  landingPage: 'reprolib:terms/landingPage',
  shuffle: 'reprolib:terms/shuffle',
  preable: 'reprolib:terms/preable',
  timeUnit: 'reprolib:terms/timeUnit',
  scoring: 'reprolib:terms/scoring',
  subScales: 'reprolib:terms/subScales',
  finalSubScale: 'reprolib:terms/finalSubScale',
  jsExpression: 'reprolib:terms/jsExpression',
  lookupTable: 'reprolib:terms/lookupTable',
  variableName: 'reprolib:terms/variableName',
  allowEdit: 'reprolib:terms/allowEdit',
  enableNegativeTokens: 'reprolib:terms/enableNegativeTokens',
};
